FROM node:latest AS build
WORKDIR /build

# Change the path to the name of your App folder and your folder containing your ReactJs
COPY Frontend_App/app_name/package.json package.json
COPY Frontend_App/app_name/package-lock.json package-lock.json
RUN npm install
RUN npm ci

# Change the path to the name of your App folder and your folder containing your ReactJs
COPY Frontend_App/app_name/public public
COPY Frontend_App/app_name/src/ src
RUN npm run build

FROM nginx:alpine

# Nginx configuration :
# Change the path to the name of your App folder and your folder containing your ReactJs
COPY Frontend_App/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /build/build/ /usr/share/nginx/html
EXPOSE 8083
CMD ["nginx", "-g", "daemon off;"]