version: '3.9'
#################### NETWORKS ####################
networks:
  frontend_net:
    name: "frontend_net"
  backend_net:
    name: " backend_net"

#################### SERVICES ####################
services:
  #################### BACKEND ####################
  backend_app:
    container_name: nodeJsApp
    build:
      context: .
      dockerfile: ./Backend_App/DockerFile
    env_file: .env
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
    networks:
      - backend_net
      - frontend_net
    volumes:
       - ./Backend_App/uploads:/app/uploads
    restart: unless-stopped

  #################### FRONTEND ####################
  frontent_app:
    container_name: reactJsApp
    build:
      context: .
      dockerfile: ./Frontend_App/DockerFile
    ports:
      - "8083:80"
    networks:
      - frontend_net
      - backend_net
    depends_on:
      - backend_app
    restart: unless-stopped

  #################### DATABASE ####################